"""Initial listings, inserted when the collection is empty."""
from models import Listing


def seed_listings() -> list[Listing]:
    return [
            # Rentals
            Listing(
                kind="rental",
                title="Grosszügige Dach-Wohnung, sehr zentral",
                address="Trischlistrasse 16",
                zip="9400",
                city="Rorschach",
                net_rent=1155,
                utilities=275,
                available_from="2026-07-01",
                status="available",
                rooms=4.5,
                area=115,
                year=2008,
                pdf_url="https://www.immo-traeum.li/Objekte/Obj218.pdf",
                image_url="/media/dachwohnung-800.webp",
                video_url="/media/dachwohnung.mp4",
                description="Ausgebauter Dachstock mit hochwertiger Ausstattung, viel Tageslicht, ruhige zentrale Lage in Rorschach.",
                lat=47.47791290283203,
                lng=9.488584518432617,
                highlight=True,
                order=1,
            ),
            Listing(
                kind="rental",
                title="Naturkeller Lagerraum 18 m²",
                address="Reitbahnstrasse 39",
                zip="9400",
                city="Rorschach",
                net_rent=50,
                utilities=10,
                available_from="2026-08-01",
                status="available",
                area=18,
                pdf_url="https://www.immo-traeum.li/Objekte/Obj2214.pdf",
                image_url="/media/lagerraum-800.webp",
                video_url="/media/lagerraum.mp4",
                description="Kühler Naturkeller, ideal für Wein, Vorräte oder Archiv.",
                lat=47.47550964355469,
                lng=9.487098693847656,
                order=2,
            ),
            # References
            Listing(
                kind="reference",
                title="Totalsanierung historisches Landhaus (1726)",
                address="7104 Arezen GR",
                city="Arezen",
                year=2013,
                status="reference",
                image_url="/media/landhaus-800.webp",
                video_url="/media/landhaus.mp4",
                description="Behutsame Totalsanierung eines Kulturguts aus dem Jahr 1726 unter Wahrung der originalen Bausubstanz.",
                order=10,
                highlight=True,
            ),
            Listing(
                kind="reference",
                title="Balkonsanierung / Umbau Ex-Bar zu 4.5-Zi-Wohnung",
                address="Reitbahnstrasse 39, Rorschach",
                city="Rorschach",
                year=2015,
                status="reference",
                description="Konversion einer ehemaligen Bar in eine grosszügige Wohnung inkl. neuer Balkonanlage.",
                order=11,
            ),
            Listing(
                kind="reference",
                title="Räumung & Innensanierung 8 Wohnungen",
                address="Reitbahnstrasse 39, Rorschach",
                city="Rorschach",
                year=2013,
                status="reference",
                description="Komplette Innensanierung von acht Wohneinheiten inkl. Neuordnung der Grundrisse.",
                order=12,
            ),
            Listing(
                kind="reference",
                title="Umbau ehemalige Druckerei zu 4-Zi-Wohnung",
                address="Gerenstrasse 9, Rorschach",
                city="Rorschach",
                year=2012,
                status="reference",
                description="Loft-artige Umnutzung eines Gewerbeobjekts zu einer charakterstarken Familienwohnung.",
                order=13,
            ),
            Listing(
                kind="reference",
                title="Ausbau Dachstock zur Wohnung",
                address="Trischlistrasse 16, Rorschach",
                city="Rorschach",
                year=2008,
                status="reference",
                description="Neuer Wohnraum unter dem Dach mit optimaler Belichtung und hochwertiger Ausstattung.",
                order=14,
            ),
        ]
